incomplete:
  prs:
    comment: >
      @{issue-author}, the issue does not contain enough information
      to reproduce the bug. Please open a new bug report and describe
      the issue in detail.
    close: true

-incomplete:
  prs:
    reopen: true

'review request':
  prs:
    reviewers:
      - mpg-toshimaru-enomoto
    number-of-reviewers: 1

heated:
  comment: >
    The thread has been temporarily locked.
    Please follow our community guidelines.
  lock: true
  lock-reason: 'too heated'

-heated:
  unlock: true
