name: 'Label to Actions'
description: 'Perform actions when issues or pull requests are labeled or unlabeled'
author: 'Armin Sebastian & Toshimaru'

inputs:
  github-token:
    description: 'GitHub access token'
    default: '${{ github.token }}'
  config-path:
    description: 'Configuration file path'
    default: '.github/label-actions.yml'
  process-only:
    description: 'Process label events only for issues or pull requests, value must be either `issues` or `prs`'
    default: ''

runs:
  using: node20
  main: dist/index.js

branding:
  icon: 'tag'
  color: 'purple'
