name: Create release

on: create

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-18.04
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '.')
    steps:
      - name: Create GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: >
            Learn more about this release from the [changelog](https://github.com/toshimaru/label-actions/blob/master/CHANGELOG.md#changelog).
          draft: true
